server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: produits-service
          uri: lb://produits-service
          predicates:
            - Path=/api/produits/**
        - id: commandes-service
          uri: lb://commandes-service
          predicates:
            - Path=/api/commandes/**
        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
