server:
  port: 8082

spring:
  application:
    name: COMMANDE-SERVICE
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/commande
    username: root
    password: Nacerabali2001.
    driver-class-name: com.mysql.cj.jdbc.Driver